import Nav from "@/components/nav";
import { SanityLive, sanityFetch } from "@/sanity/lib/live";
import { ABOUT_PAGE_QUERY } from "@/sanity/lib/queries";
import localFont from "next/font/local";
import "./globals.css";

export const revalidate = 3600;

const untitledSerif = localFont({
  src: [
    {
      path: "./fonts/UntitledSerif-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/UntitledSerif-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-untitled-serif",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { data: about } = await sanityFetch({
    query: ABOUT_PAGE_QUERY,
  });

  return (
    <html lang="en" className={`${untitledSerif.variable} h-full antialiased`}>
      <body className={untitledSerif.className}>
        <Nav about={about} />
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
