import Nav from "@/components/nav";
import localFont from "next/font/local";
import "./globals.css";

const untitledSerif = localFont({
  src: [
    {
      path: "./fonts/UntitledSerif-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/UntitledSerif-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-untitled-serif",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${untitledSerif.variable} h-full antialiased`}>
      <body className={untitledSerif.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
